package com.alticelabs.ccp.prototype.util;

public enum PrototypeSteps {
    VERIFY_SERVICE_CRITERIA,
    CHECK_ELIGIBILITY_CHARGING,
    CALCULATE_RATING_CHARGING,
    CHARGING_BUCKETS_CHARGING,
    UPDATE_RECORDS_CHARGING,
    GENERATE_LDR_CHARGING,
    CREATE_REPLY_CHARGING,
    CHECK_ELIGIBILITY_AOC,
    CALCULATE_RATING_AOC,
    UPDATE_RECORDS_AOC,
    GENERATE_LDR_AOC,
    CREATE_REPLY_AOC,
    UPDATE_RECORDS_NOT_ELIGIBLE,
    GENERATE_LDR_NOT_ELIGIBLE,
    CREATE_REPLY_NOT_ELIGIBLE,
    GENERATE_LDR_INVALID_SERVICE,
    CREATE_REPLY_INVALID_SERVICE

}
